
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/microservices
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: User-Service
